### ISSUE TITLE
Naming of #[automata]

### ISSUE THREAD

**Issue by dbrgn** [rustype/typestate-rs#2]
I stumbled over the `typestate-automata` crate and noticed that the macro to mark an automaton is called `#[automata]`.

Automata is the plural form. Shouldn't this be called `#[automaton]`?

https://en.wikipedia.org/wiki/Automaton

**Comment by jmg-duarte** [comment]
You make a valid point, one my advisor also made.
I don't want to discuss what sounds better but currently I've only kept the name like that this long because I've been putting it off to "later". But I guess its time has come

**Comment by dbrgn** [comment]
In case you ever want to change it, I'd do it sooner than later, it doesn't get easier over time (once people start using this library) 🙂

**Comment by jmg-duarte** [comment]
This has been addressed in `0.7.0`
