### ISSUE TITLE
Allow exporting mermaid diagrams as files

### ISSUE THREAD

**Issue by jmg-duarte** [rustype/typestate-rs#23]

**Comment by jquesada2016** [comment]
This sounds like a fantastic idea!

Not sure what API you were thinking for exposing this? Just a thought:

```rust
#[typestate(export_diagram = "./path/to/somewhere.filetype")]
mod my_state { /* ... */ }
```

where `filetype` could be a list of supported filetypes, such as `SVG` or `JPEG`, for example.

**Comment by jmg-duarte** [comment]
Currently, the macro already supports exporting to `DOT` and `PlantUML` formats, I'd go with the same formula:
- Declare a cargo feature
- When the feature is enabled, export the file
-
