### ISSUE TITLE
Documentation: a line isn't finished

### ISSUE THREAD

**Issue by skaunov** [rustype/typestate-rs#42]
https://github.com/rustype/typestate-rs/blob/6507ea7151ebbf4e2c0caec0b6b5799f8641b57c/src/lib.rs#L209 just ends in the middle of the sentence, looks like it was lost "over 1 year ago", since I found it at <https://crates.io/crates/typestate>.

**Comment by jmg-duarte** [comment]
Nice catch @skaunov. Could you submit a PR?

**Comment by skaunov** [comment]
I wanted to, before creating an issue; but I couldn't find a correct commit before this line got trimmed, and don't know the crate well enough to finish the line on my own.
