### ISSUE TITLE
Lifetimes for a state

### ISSUE THREAD

**Issue by Bobbbay** [rustype/typestate-rs#5]
Hi there, firstly great crate and writeup.

I've been working on a compiler that uses typestate to enforce itself. For reference, here's the generated diagram for it:

![image](https://user-images.githubusercontent.com/49123594/130363546-4cffa87b-decb-4f5b-beb2-c0286a9d5a66.png)

My issue is that some of my states contain references to `str`s and other structs that need lifetimes. However, every time I try to add a lifetime, the compiler complains. For reference, here is my current layout:

```rust
#[typestate(enumerate)]
pub mod compiler {
    //! Compiler for the Salo language (enforced by typestate)
    use ariadne::Report;

    use crate::ast::Expr;

    #[automaton]
    #[derive(Debug)]
    pub struct Parser {
        pub filename: &'static str,
        pub content: &'static str,
    }

    #[state]
    pub struct Source;
    #[state]
    #[derive(Debug)]
    pub struct AST(pub Vec<Expr<'static>>);
    #[state]
    pub struct Output(pub &'static str);
    #[state]
    pub struct Error(pub Report);

    pub enum MaybeAST {
        #[metadata(label = "Parsed into AST successfully.")]
        AST,
        #[metadata(label = "Failed to parse into AST.")]
        Error,
    }

    pub enum MaybeOutput {
        #[metadata(label = "Evaluated succesfully.")]
        Output,
        #[metadata(label = "Failed to evaluate.")]
        Error,
    }

    pub trait Source {
        /// Initial state.
        fn new(filename: &'static str, content: &'static str) -> Source;

        /// Turn [`Source`] into an [`AST`].
        fn parse(self) -> MaybeAST;
    }

    pub trait AST {
        /// Turn [`AST`] into an [`Output`].
        fn evaluate(self) -> MaybeOutput;
    }

    pub trait Output {
        fn export(self) -> &'static str;
    }

    pub trait Error {
        fn report(self) -> !;
    }
}
```

Note that all of the `'static`s are where I would like the lifetime of the state to go :) (except for the `filename` and `content`, I would like those to use `Parser`'s lifetime, of course.)

This compiles like so, but once I try to give anything a lifetime, such as:

```rust
    pub struct AST<'a>(pub Vec<Expr<'static>>);
```

I get:

```
error[E0726]: implicit elided lifetime not allowed here
  --> crates/saloc/src/compiler.rs:27:16
   |
27 |     pub struct AST<'a>(pub Vec<Expr<'static>>);
   |                ^^^- help: indicate the anonymous lifetime: `<'_>`
   |
   = note: assuming a `'static` lifetime...

error[E0726]: implicit elided lifetime not allowed here
   --> crates/saloc/src/compiler.rs:148:26
    |
148 | impl ASTState for Parser<AST> {
    |                          ^^^- help: indicate the anonymous lifetime: `<'_>`
    |
    = note: assuming a `'static` lifetime...

error[E0106]: missing lifetime specifier
  --> crates/saloc/src/compiler.rs:35:9
   |
35 |         AST,
   |         ^^^ expected named lifetime parameter
   |
help: consider introducing a named lifetime parameter
   |
33 ~     pub enum MaybeAST<'a> {
34 |         #[metadata(label = "Parsed into AST successfully.")]
35 ~         AST<'a>,
   |

error[E0106]: missing lifetime specifier
  --> crates/saloc/src/compiler.rs:27:16
   |
27 |     pub struct AST<'a>(pub Vec<Expr<'static>>);
   |                ^^^ expected named lifetime parameter
   |
help: consider introducing a named lifetime parameter
   |
18 ~     pub struct Parser<'a> {
19 |         pub filename: &'static str,
20 |         pub content: &'static str,
21 |     }
22 |
23 |     #[state]
 ...

For more information about this error, try `rustc --explain E0106`.
```

Some notes on these errors:

 1. Seems interesting to me, but we'll see what happens once we add an anonymous lifetime
 2. Makes sense, but springs off of error no. 1 
 3. :+1:
 4. :+1:

Let's try to (naively) and fix our code according to the feedback above. First, an easy one:

```rust
    pub enum MaybeAST<'a> {
        #[metadata(label = "Parsed into AST successfully.")]
        AST<'a>,
        #[metadata(label = "Failed to parse into AST.")]
        Error,
    }
```

Compiling this makes things even better (just kidding):

```
error: expected one of `(`, `,`, `=`, `{`, or `}`, found `<`
  --> crates/saloc/src/compiler.rs:35:12
   |
35 |         AST<'a>,
   |            ^ expected one of `(`, `,`, `=`, `{`, or `}`

error: expected item, found `'a`
  --> crates/saloc/src/compiler.rs:35:13
   |
35 |         AST<'a>,
   |             ^^ expected item

warning: unused `#[macro_use]` import
 --> crates/saloc/src/lib.rs:9:1
  |
9 | #[macro_use]
  | ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0432]: unresolved import `crate::compiler::compiler`
  --> crates/saloc/src/lib.rs:25:26
   |
25 |     use crate::compiler::compiler::*;
   |                          ^^^^^^^^ could not find `compiler` in `compiler`

error[E0433]: failed to resolve: use of undeclared type `MaybeAST`
  --> crates/saloc/src/lib.rs:39:17
   |
39 |                 MaybeAST::AST(ast) => ast,
   |                 ^^^^^^^^ use of undeclared type `MaybeAST`

error[E0433]: failed to resolve: use of undeclared type `MaybeAST`
  --> crates/saloc/src/lib.rs:40:17
   |
40 |                 MaybeAST::Error(error) => {
   |                 ^^^^^^^^ use of undeclared type `MaybeAST`

error[E0433]: failed to resolve: use of undeclared type `Parser`
  --> crates/saloc/src/lib.rs:36:26
   |
36 |             let parser = Parser::<Source>::new("<testin>", content);
   |                          ^^^^^^ not found in this scope
   |

error[E0412]: cannot find type `Source` in this scope
  --> crates/saloc/src/lib.rs:36:35
   |
36 |             let parser = Parser::<Source>::new("<testin>", content);
   |                                   ^^^^^^ not found in this scope
   |
```

In the first few errors, it seems like the lifetime generic arguemnt to AST wasn't expected at all.

Anyways, we can go down the rabbit hole quite a bit, but I have not found any working solutions. However, it's evident that state + lifetimes *is* possible, and even the Drone example [has a reference with a lifetime in it](https://github.com/rustype/drone/blob/main/src/ref_drone.rs#L4). On the other hand, it seems to me that whenever one of the examples for typestate wants to use an `&str`, it uses a `String` instead, like [in the auction example](https://github.com/rustype/typestate-examples/blob/main/auction/src/main.rs#L28).

On this specific project, I'm ~alright with using `String`s for now, but honestly it's an extra heap allocation for nothing.

I'm thinking, maybe it's not possible to have lifetimes in states and automata because the macro doesn't support it? Or, am I doing something wrong? Honestly, it's probably the latter.

**Comment by jmg-duarte** [comment]
Hello @Bobbbay! 

It makes me super happy that someone is using this project for a real-world use case!

Currently, `typestate` does not support lifetimes, however I would be very happy to implement support for them!
To make my work easier, could you provide some small examples and expected expansion output?

**Comment by jmg-duarte** [comment]
I have just updated the crate, please try with version [`0.9.0-rc1`](https://crates.io/crates/typestate/0.9.0-rc1)

**Comment by Bobbbay** [comment]
Hi, so sorry for the late message... :)

`0.9.0-rc1` looks great! However, I'm still having some problems. I believe now the `enum`s for potential states (in the following example, `MaybeAST`), don't seem to parse the lifetimes either.

[Here is basically what I'd like to see](https://github.com/semc-labs/salo/blob/typestate-experiments/crates/saloc-lib/src/compiler.rs#L27).

Important to note there: 
 * AST has a lifetime of `'a`, which it should inherit from Parser. 
 * AST's first tuple argument, the Vec of Exprs, requires a lifetime, and is given `'a`.
 * `MaybeAST` has a variant of `AST`, which of course requires a lifetime. Hence, `MaybeAST` needs a lifetime argument, too.

Error message, now:

```
error: expected one of `(`, `,`, `=`, `{`, or `}`, found `<`
  --> crates/saloc-lib/src/compiler.rs:35:12
   |
35 |         AST<'a>,
   |            ^ expected one of `(`, `,`, `=`, `{`, or `}`

error: expected item, found `'a`
  --> crates/saloc-lib/src/compiler.rs:35:13
   |
35 |         AST<'a>,
   |             ^^ expected item
```

[Here](https://github.com/semc-labs/salo/commit/1cd81092a8452ed49042c9e43b256d4db831b37e#diff-731e1d09a2f3242bdaea80be4db4a54644a64c350c601a127f0928a96f75102e) is the diff of the file from `'static` lifetimes. As a side note, should I be changing/adding any other lifetime arguments anywhere else throughout that file?

**Comment by jmg-duarte** [comment]
Hello again!

No worries about the `enum`, I'm working on it and bit by bit I'll implement this feature.

Regarding the enum lifetimes, I think I could infer them.
Given that structures are checked first, we can store the `ItemStruct` and then expand the enumeration with the lifetimes.
Example:
```rust
struct StateWithLifetime<'lifetime>(&'lifetime str);

enum EnumWithoutLifetimes {
    StateWithLifetimes
}
```
Expands to:
```rust
struct StateWithLifetime<'lifetime>(&'lifetime str);

enum EnumWithoutLifetimes<'lifetime> {
    StateWithLifetimes<'lifetime>
}
```

**Comment by jmg-duarte** [comment]
Version `0.9.0-rc2` addresses the previous issue and adds generic parameters "inference" to enumerations.
This means that the previous example compiles, furthermore we can write enumerations with lifetimes (and possibly generic parameters) as simple types in function returns.
```rust
use typestate_proc_macro::typestate;
#[typestate]
mod m {
    #[automaton]
    struct Player {}

    #[state]
    struct Alive<'name> {
        name: &'name str
    }

    #[state]
    struct Dead<'name> {
        name: &'name str
    }

    enum PlayerLifeState {
        Alive,
        Dead,
    }

    trait Alive<'name> {
        fn start(name: &str) -> Alive;
        fn damage(self) -> PlayerLifeState;
        fn suicide(self) -> Dead<'name>;
    }

    trait Dead {
        fn end(self);
    }
}

fn main() {}
```
Now expands to:
```rust
mod m {
    struct Player<State: PlayerState> {
        pub state: State,
    }
    struct Alive<'name> {
        name: &'name str,
    }
    struct Dead<'name> {
        name: &'name str,
    }
    enum PlayerLifeState<'name> {
        Alive(Player<Alive<'name>>),
        Dead(Player<Dead<'name>>),
    }
    trait AliveState<'name> {
        fn start(name: &str) -> Player<Alive>;
        #[must_use]
        fn damage(self) -> PlayerLifeState<'name>;
        #[must_use]
        fn suicide(self) -> Dead<'name>;
    }
    trait DeadState {
        fn end(self);
    }
    #[doc(hidden)]
    mod __private {
        pub trait PlayerState {}
    }
    pub trait PlayerState: __private::PlayerState {}
    impl<__T: ?::core::marker::Sized> PlayerState for __T where __T: __private::PlayerState {}
    impl<'name> __private::PlayerState for Alive<'name> {}
    impl<'name> __private::PlayerState for Dead<'name> {}
}
fn main() {}
```

The trait still requires the parameters (lifetimes and generics) to be present though, if you have an idea on how to address it, please share.

**Comment by jmg-duarte** [comment]
Could vou confirm that it fixes your problem?

**Comment by Bobbbay** [comment]
Sorry, I'm away from my laptop until this Tuesday. However, I'm fairly certain everything is fine, so I'll reopen only if needed :). Thank you for the awesome work!
