### ISSUE TITLE
Examples or Documentation for `#[typestate(enumerate = "...")]` and `#[typestate(state_constructors)]`?

### ISSUE THREAD

**Issue by jquesada2016** [rustype/typestate-rs#7]
First of all, great macro!

I am trying to understand what these two attribute metadata parameters do? I searched through the 3 available examples, but non of them used those there.

Another example for the two topics mentioned in the `Advanced Guide` would be also much appreciated.

**Comment by jmg-duarte** [comment]
Hello! Thank you for your interest, you're right, examples are missing.

Do you have suggestions regarding placement? Should I add them in the `README.md`, `docs.rs`, maybe a wiki?

**Comment by jquesada2016** [comment]
I personally have seen two methods of documentation that work very well. Either document everything with examples inline with the code (rust doc), or create a short book. Since this is a bare macro crate, I would strongly suggest the latter. I am more than happy to help out wherever you need me!

In this case, it really would be a short book that would demonstrate the macro syntax and a small real-world use case that introduces all of the syntaxes used by this crate, i.e. states, indeterminant states, etc.

**Comment by jmg-duarte** [comment]
The book suggestion is great, it would be an amazing resource for people using the macro! 
I say we can address this after I get the generics implementation done!

**Comment by jmg-duarte** [comment]
@jquesada2016 I started developing a book, you can help me work on it by writing documentation into https://github.com/rustype/typestate-rs/tree/140f232/typestate-book

I am open to suggestions regarding the structure!

**Comment by jmg-duarte** [comment]
While still a work in progress, I've started writing the book. It's still missing the examples this issue asks for however you can already read it in https://rustype.github.io/typestate-rs/

**Comment by jquesada2016** [comment]
This is good stuff! I read it and do have some suggestions! I will go ahead and hopefully create a pull request today.

**Comment by jmg-duarte** [comment]
This has been address in https://github.com/rustype/typestate-rs/commit/c547ae5e8e0086e51875eccdd47a074ca86cdd6c
